// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace api_ef.Data.Models;

public partial class ComercioDBContext : DbContext
{
    public ComercioDBContext(DbContextOptions<ComercioDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Articulo> Articulos { get; set; }

    public virtual DbSet<DetallesFactura> DetallesFacturas { get; set; }

    public virtual DbSet<Factura> Facturas { get; set; }

    public virtual DbSet<FormasDePago> FormasDePagos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Articulo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_articulos");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.EstaActivo).HasColumnName("estaActivo");
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.PrecioUnitario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precioUnitario");
        });

        modelBuilder.Entity<DetallesFactura>(entity =>
        {
            entity.HasKey(e => new { e.IdDetalle, e.IdFactura }).HasName("pk_detallesFactura");

            entity.ToTable("DetallesFactura");

            entity.Property(e => e.IdDetalle)
                .ValueGeneratedOnAdd()
                .HasColumnName("idDetalle");
            entity.Property(e => e.IdFactura).HasColumnName("idFactura");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.IdArticulo).HasColumnName("idArticulo");

            entity.HasOne(d => d.IdArticuloNavigation).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.IdArticulo)
                .HasConstraintName("fk_detallesFactura_articulo");

            entity.HasOne(d => d.IdFacturaNavigation).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.IdFactura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_detallesFactura_factura");
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.NroFactura).HasName("pk_factura");

            entity.Property(e => e.NroFactura).HasColumnName("nroFactura");
            entity.Property(e => e.Cliente)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("cliente");
            entity.Property(e => e.FacturaActiva).HasColumnName("facturaActiva");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.IdForma).HasColumnName("idForma");

            entity.HasOne(d => d.IdFormaNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdForma)
                .HasConstraintName("fk_factura_forma");
        });

        modelBuilder.Entity<FormasDePago>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_formasdepago");

            entity.ToTable("FormasDePago");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.EstaActivo).HasColumnName("estaActivo");
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}