// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api_ef.Data.Models;

public partial class Factura
{
    public int NroFactura { get; set; }

    public DateOnly? Fecha { get; set; }

    public int? IdForma { get; set; }

    public string Cliente { get; set; }

    public bool? FacturaActiva { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual FormasDePago IdFormaNavigation { get; set; }
}