// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using api_ef.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace api_ef.Data.Models
{
    public partial interface IComercioDBContextProcedures
    {
        Task<int> SP_ACTUALIZAR_FACTURAAsync(int? nroFactura, string cliente, int? idForma, bool? facturaActiva, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_GUARDAR_ARTICULOAsync(int? id, string nombre, decimal? precioUnitario, bool? estaActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_GUARDAR_FORMAPAGOAsync(int? id, string nombre, bool? estaActivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_INSERTAR_DETALLEAsync(int? nroFactura, int? idArticulo, int? cantidad, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_INSERTAR_FACTURAAsync(string cliente, int? idForma, bool? facturaActiva, OutputParameter<int?> nroFactura, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_ARTICULOSResult>> SP_RECUPERAR_ARTICULOSAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_ARTICULOS_POR_CODIGOResult>> SP_RECUPERAR_ARTICULOS_POR_CODIGOAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_FACTURA_POR_IDResult>> SP_RECUPERAR_FACTURA_POR_IDAsync(int? nroFactura, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_FACTURASResult>> SP_RECUPERAR_FACTURASAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_FORMAPAGO_POR_CODIGOResult>> SP_RECUPERAR_FORMAPAGO_POR_CODIGOAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RECUPERAR_FORMASPAGOResult>> SP_RECUPERAR_FORMASPAGOAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_REGISTRAR_BAJA_ARTICULOAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_REGISTRAR_BAJA_FACTURAAsync(int? nroFactura, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_REGISTRAR_BAJA_FORMAPAGOAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
