// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace api_ef.Data.Models
{
    public partial class SP_RECUPERAR_FORMASPAGOResult
    {
        public int id { get; set; }
        [StringLength(50)]
        public string nombre { get; set; }
        public bool? estaActivo { get; set; }
    }
}
