// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace api_ef.Data.Models
{
    public partial class SP_RECUPERAR_FACTURASResult
    {
        public int NroFactura { get; set; }
        public DateOnly? fecha { get; set; }
        public int? IdFormaPago { get; set; }
        public int DetalleId { get; set; }
        public int? cantidad { get; set; }
        public int ArticuloId { get; set; }
        [StringLength(50)]
        public string NombreArticulo { get; set; }
        [Column("PrecioArticulo", TypeName = "decimal(10,2)")]
        public decimal? PrecioArticulo { get; set; }
        public int FormaPagoId { get; set; }
        [StringLength(50)]
        public string NombreFormaPago { get; set; }
    }
}
